version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  web:
    build: ..
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nextgenapp
      - NEXT_PUBLIC_GRAPHQL_ENDPOINT=http://localhost:3000/api/graphql
    depends_on:
      - mongo

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../public:/usr/share/nginx/html:ro
    depends_on:
      - web

volumes:
  mongo-data:
